model: 
  name: bert
  model_size_bytes: 4034713312

framework: tensorflow

workflow:
  generate_data: False
  train: True
  debug: False
  checkpoint: False 
 
dataset: 
  data_folder: data/bert_vx
  format: vortex
  num_files_train: 50
  num_samples_per_file: 313532
  record_length_bytes: 2500
  file_prefix: part

train:
  seed_change_epoch: False
  computation_time: 0.00268
  total_training_steps: 1
 
reader:
  data_loader: tensorflow
  read_threads: 1
  computation_threads: 1
  transfer_size: 262144
  batch_size: 80000
  file_shuffle: seed
  sample_shuffle: seed

checkpoint:
  checkpoint_folder: checkpoints/bert
  steps_between_checkpoints: 250
